Refactored group_sliders method
SABS-R3-Epidemiology/seirmo pull request #45
Opened 2020-12-16 05:51 UTC by FarmHJ

2020-12-16 09:01 UTC, DavAug requested changes
Really good job @FarmHJ ! I just made a comment about the assert that one slider can only belong to one group, and a couple style comments that may be helpful.

2020-12-16 09:01 UTC, DavAug commented on seirmo/tests/test_slider.py
> +        self.assertEqual(len(slider().children[1].children[2].children), 2)
that's exactly what I had in mind. Very good!

2020-12-17 12:51 UTC, FarmHJ commented on seirmo/apps/_slider.py
> +        for group_id in list(self._group_ids.keys()):
If I understand it correctly, changing it this way would change the grouping of the sliders

2020-12-17 12:53 UTC, FarmHJ commented on seirmo/apps/_slider.py
> +        for group_id in list(self._group_ids.keys()):
Sorry about that, now I understand what you are trying to say.

2020-12-17 13:48 UTC, DavAug approved these changes
Very nice @FarmHJ ! I just have one super minor comment on the variable names, see below.

2020-12-17 13:48 UTC, DavAug commented on seirmo/apps/_slider.py
> +            for slider_members in slider_id:
sliders_ids? This is more than one slider isn't it?

2020-12-17 13:48 UTC, DavAug commented on seirmo/apps/_slider.py
> +            for slider_members in slider_id:
and then maybe slider_member, because this is only one slider

2020-12-17 14:11 UTC, merged